# TerraLogic Tech - Manual Product Configuration
# Your products are configured below

products:
  # ============================================
  # OFFICE CHAIRS
  # ============================================
  chairs:
    - name: "COMHOMA Executive Ergonomic Office Chair with Footrest"
      asin: "B0FP28DWVQ"
      price_range: "$100-150"
      tier: "mid"
      description: "Comfortable executive office chair with built-in footrest and ergonomic design. Perfect for long work sessions at home."
      features:
        - "Built-in adjustable footrest"
        - "Ergonomic lumbar support"
        - "Adjustable armrests"
        - "360-degree swivel"
      image_url: ""
      affiliate_url: "https://www.amazon.com/dp/B0FP28DWVQ?tag=bestpickshu03-20"
      rating: 4.5
      review_count: 500

    # Add more chairs here - just copy the format above

  # ============================================
  # DESKS
  # ============================================
  desks:
    - name: "Electric Standing Desk with Memory Preset"
      asin: "B07DEF789"
      price_range: "$300-500"
      tier: "mid"
      description: "Adjustable height desk that transitions smoothly from sitting to standing. Memory presets let you save your favorite heights."
      features:
        - "Electric height adjustment"
        - "Memory preset buttons"
        - "Spacious desktop (48x24 inches)"
        - "Sturdy steel frame"
      image_url: ""
      affiliate_url: "https://www.amazon.com/dp/B07DEF789?tag=bestpickshu03-20"
      rating: 4.6
      review_count: 800

    # Add more desks here

  # ============================================
  # MONITORS
  # ============================================
  monitors:
    - name: "27-inch 4K UHD Monitor"
      asin: "B08GHI012"
      price_range: "$300-400"
      tier: "mid"
      description: "Crystal-clear 4K display perfect for productivity and content creation. HDMI and DisplayPort connectivity."
      features:
        - "27-inch 4K UHD (3840x2160)"
        - "IPS panel with wide viewing angles"
        - "HDR10 support"
        - "Multiple ports (HDMI, DP, USB-C)"
      image_url: ""
      affiliate_url: "https://www.amazon.com/dp/B08GHI012?tag=bestpickshu03-20"
      rating: 4.7
      review_count: 1200

    # Add more monitors here

  # ============================================
  # LIGHTING
  # ============================================
  lighting:
    - name: "LED Desk Lamp with USB Charging Port"
      asin: "B09JKL345"
      price_range: "$30-50"
      tier: "budget"
      description: "Adjustable LED desk lamp with multiple brightness levels and color temperatures. Built-in USB port for charging devices."
      features:
        - "Adjustable arm and head"
        - "5 brightness levels"
        - "3 color temperature modes"
        - "USB charging port"
      image_url: ""
      affiliate_url: "https://www.amazon.com/dp/B09JKL345?tag=bestpickshu03-20"
      rating: 4.4
      review_count: 600

    # Add more lighting here

  # ============================================
  # AUDIO & VIDEO
  # ============================================
  audio-video:
    - name: "1080p HD Webcam with Built-in Microphone"
      asin: "B08MNO678"
      price_range: "$60-100"
      tier: "mid"
      description: "Clear 1080p video quality for video calls and streaming. Auto-focus and light correction ensure you always look your best."
      features:
        - "Full HD 1080p at 30fps"
        - "Auto-focus and light correction"
        - "Built-in dual microphones"
        - "Works with all video platforms"
      image_url: ""
      affiliate_url: "https://www.amazon.com/dp/B08MNO678?tag=bestpickshu03-20"
      rating: 4.5
      review_count: 900

    # Add more audio-video products here
